version: "3.7"

services:
    mongo:
      image: mongo
      container_name: Skripsi-BJ-Database
      environment:
        - MONGO_INITDB_DATABASE=Auth
        - MONGO_INITDB_ROOT_USERNAME=Wiratama
        - MONGO_INITDB_ROOT_PASSWORD=751862943
      ports:
        - 27017:27017
      volumes:
        - ./mongo/db:/data/db
    nginx:
      image: nginx
      container_name: Skripsi-BJ-Nginx
      ports:
        - 80:80
      volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./nginx/html:/usr/share/nginx/html